const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { canonicalizeCandidate, fixSource } = require('../dist');
const { analyzeFiles } = require('../dist/language-server');
const { applyChanges, applyConflictChanges } = require('../dist/edits');
assert.equal(canonicalizeCandidate('gap-[18px]'), 'gap-4.5');
assert.equal(canonicalizeCandidate('hover:bg-[var(--brand)]'), 'hover:bg-(--brand)');
assert.equal(canonicalizeCandidate('bg-(--background)'), 'bg-background');
assert.equal(canonicalizeCandidate('text-(--primary)'), 'text-primary');
assert.equal(canonicalizeCandidate('hover:bg-(--accent)'), 'hover:bg-accent');
const result = fixSource('<div className="gap-[18px]" />');
assert.equal(result.source, '<div className="gap-4.5" />');
assert.equal(result.changes[0].line, 1);
console.log('twcheck smoke tests passed');

(async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'twcheck-'));
  const css = path.join(root, 'app.css');
  const nestedDir = path.join(root, 'src', 'components');
  const file = path.join(nestedDir, 'page.tsx');
  const conflictFile = path.join(nestedDir, 'conflict.tsx');
  fs.mkdirSync(nestedDir, { recursive: true });
  fs.writeFileSync(css, '@import "tailwindcss"; @theme inline { --color-primary: var(--primary); }');
  fs.writeFileSync(file, '<div className="text-(--primary) gap-[18px]" />');
  fs.writeFileSync(conflictFile, '<div className="leading-4.75 leading-6" />');
  const issues = await analyzeFiles([file, conflictFile], { cwd: root, cssPath: css });
  const canonicalIssues = issues.filter(issue => issue.type === 'canonical');
  const conflictIssues = issues.filter(issue => issue.type === 'conflict');
  assert.deepEqual(canonicalIssues.map(issue => issue.canonical), ['text-primary', 'gap-4.5']);
  assert.equal(conflictIssues.length, 2);
  const nestedResult = applyChanges(file, canonicalIssues);
  fs.writeFileSync(file, nestedResult.fixed);
  assert.equal(fs.readFileSync(file, 'utf8'), '<div className="text-primary gap-4.5" />');
  const conflictResult = applyConflictChanges(conflictFile, conflictIssues);
  fs.writeFileSync(conflictFile, conflictResult.fixed);
  assert.equal(fs.readFileSync(conflictFile, 'utf8'), '<div className="leading-6" />');
  fs.rmSync(root, { recursive: true, force: true });
  console.log('official Tailwind diagnostics, directory fix, and css conflict tests passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
